words:
  - avenir
  - cdylib
  - clsx
  - codegen
  - evenodd
  - fluentui
  - givemitoken
  - grayscale
  - icns
  - Iconify
  - Mingxuan
  - njsproj
  - ntvs
  - reekystive
  - rgba
  - rlib
  - serde
  - staticlib
  - tauri
  - Vite
  - WCAG
  - xlink
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
  - Cargo.lock
